#47 all
zdimon/pressa-besa pull request #49
Opened 2022-02-19 12:33 UTC by Nizhurin

2022-02-19 12:35 UTC, zdimon requested changes, later dismissed
исправить урлы в шапке

2022-02-19 12:47 UTC, zdimon approved these changes

2022-02-19 12:47 UTC, zdimon commented on backend/catalog/views.py
> +    if category != 'all':
Исправить урлы в шапке

2022-02-19 12:48 UTC, zdimon requested changes
надо поменять урлы в линках в шапке

2022-02-19 12:48 UTC, Nizhurin commented
nbgf cltkfk

2022-02-19 18:34 UTC, Nizhurin commented
Issue #47 Done!

2022-02-20 12:02 UTC, zdimon approved these changes

2022-02-20 12:03 UTC, merged